### ISSUE TITLE
NumberFormatException when checking some Artifacts

### ISSUE THREAD

**Issue by kij** [xsc/lein-ancient#44]
Sorry for not catching this before 0.6.0  The 0.6.0-snaphot (pre chrismas) i was using worked as expected.

On this miminal project.clj, lein ancient 0.6.0 and (newer 0.6.0-snapshots) fails with 
```(error) #<ExecutionException java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "20141107165303">```

```clojure
(defproject bam "1b"
  :description "bam"
  :dependencies [[io.intercom/intercom-java "1.0.0"]]
  :repositories [["jcenter" {:url "http://jcenter.bintray.com"}]])
```

lein-ancient 0.5.5 returns 
```
 [io.intercom/intercom-java "1.0.1"] is available but we use "1.0.0"]
```

**Comment by xsc** [comment]
> Sorry for not catching this before 0.6.0 [...]

No problem, that should generally be my job, I suppose. ;)

The thing is actually a bug in version-clj (and always should have been but maybe older versions of lein-ancient had more `try`/`catch` safeguards in place) which tries to parse e.g. this version:

```
0.0.1-20141002100138
```

and fails when running

```clojure
(Integer/parseInt "20141002100138")
;; => #<NumberFormatException ...>
```

**Comment by xsc** [comment]
While this is fixed now, a problem remains, namely that e.g. `1.0.1-1` is treated as a newer (release!) version than `1.0.1` since version-clj expects non-release versions to have at least one non-numeric component.

If the versions with timestamp in your repository are actually SNAPSHOTs, lein-ancient will (at least for now) not treat them correctly I'm afraid.

**Comment by xsc** [comment]
Released in

```clojure
[lein-ancient "0.6.1"]
```
