### ISSUE TITLE
Error code when deps are outdated

### ISSUE THREAD

**Issue by donbonifacio** [xsc/lein-ancient#55]
Is there a way to return an error status code? I want my build to fail if deps are outdated. With the basic usage I get an ok status code.

```
lein ancient
[compojure "1.3.4"] is available but we use "1.3.3"
[time 14s, exit 0]
```

**Comment by xsc** [comment]
I think it should be reasonable to return a non-zero status code there.

**Comment by xsc** [comment]
@donbonifacio Sorry for the delay! Could you try the latest SNAPSHOT?

```clojure
[lein-ancient "0.6.8-SNAPSHOT"]
```

**Comment by donbonifacio** [comment]
```
$ lein ancient
[clanhr/postgres-gateway "0.9.3"] is available but we use "0.9.2"
[time 11s, exit 1]
```

Workin' :)
Thanks.

**Comment by robertkuhar** [comment]
I don't think its reasonable that this is now the default behavior.  Geez.  Now my builds fail for what is otherwise just an operational message; like logging.  Is there a way to option out of this behavior?

tcc-rkuhar:scouting-utils robert.kuhar$ lein do clean, deps, compile, test, ancient

lein test scouting-utils.core-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
(warn)  [climate] - Δ  923ms - failure when checking com.climate/tcc-config: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): text/plain
(warn)  [climate] - Δ  969ms - failure when checking cheshire/cheshire: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): text/plain
[ch.qos.logback/logback-classic "1.1.8"] is available but we use "1.1.7"
[clj-http "3.4.1"] is available but we use "2.2.0"
[cheshire "5.6.3"] is available but we use "5.6.1"
[com.amazonaws/aws-java-sdk-s3 "1.11.70"] is available but we use "1.11.20"
[com.amazonaws/aws-java-sdk-dynamodb "1.11.70"] is available but we use "1.11.20"
[clj-time "0.12.2"] is available but we use "0.12.0"
tcc-rkuhar:scouting-utils robert.kuhar$ echo $?
1

**Comment by donbonifacio** [comment]
Hey @robertkuhar ,

Can you split the `lein ancient` part in a new command? You can ignore the status code like this:

`lein ancient || true`

**Comment by xsc** [comment]
[Linking Issue #77]

**Comment by robertkuhar** [comment]
I can...good idea.  Thanks.

Bob
