### ISSUE TITLE
Error when checking snacktory

### ISSUE THREAD

**Issue by Immortalin** [xsc/lein-ancient#62]
Hi, I am getting this error when I try to utilize the [snacktory](https://github.com/karussell/snacktory) [repository](https://github.com/karussell/mvnrepo).

```
(warn)  [karussell_releases] - Δ 7011ms - failure when checking de.jetwick/snacktory: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): text/plain
```

**Comment by xsc** [comment]
@Immortalin The problem is that the `maven-metadata.xml` does not have an XML content type set:

```
$ curl -I  https://raw.githubusercontent.com/karussell/mvnrepo/master/releases/de/jetwick/snacktory/maven-metadata.xml 
HTTP/1.1 200 OK
...
ETag: "68ef9513139ec1cc203b18e64b6cedcdc9803eba"
Content-Type: text/plain; charset=utf-8
...
```

I think it is sane behaviour to expect that a Maven repository serves its files with appropriate HTTP headers - but I can see how this is a problem in this case... Maybe you could use something like RawGit to point to the repository?

```
https://rawgit.com/karussell/mvnrepo/master/releases/
```

**Comment by Immortalin** [comment]
Thank you
