### ISSUE TITLE
Add option to force exit code 0

### ISSUE THREAD

**Issue by robertkuhar** [xsc/lein-ancient#77]
lein-ancient has always been more of an informational utility for us than something we wanted to fail a build.  By 0.6.10 it had gained the unpleasant default behavior of posting an ERRNO of non zero if it found something wrong with the dependencies.  To me this breaks backward compatibility.  I would like to see the default behavior restored and have this "fail the build if lien-ancient fails" be some sort of option in thing.  

`
tcc-rkuhar:scouting-utils robert.kuhar$ lein do clean, deps, compile, test, ancient

lein test scouting-utils.core-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
(warn)  [climate] - Δ  923ms - failure when checking com.climate/tcc-config: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): text/plain
(warn)  [climate] - Δ  969ms - failure when checking cheshire/cheshire: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): text/plain
[ch.qos.logback/logback-classic "1.1.8"] is available but we use "1.1.7"
[clj-http "3.4.1"] is available but we use "2.2.0"
[cheshire "5.6.3"] is available but we use "5.6.1"
[com.amazonaws/aws-java-sdk-s3 "1.11.70"] is available but we use "1.11.20"
[com.amazonaws/aws-java-sdk-dynamodb "1.11.70"] is available but we use "1.11.20"
[clj-time "0.12.2"] is available but we use "0.12.0"
tcc-rkuhar:scouting-utils robert.kuhar$ echo $?
1
`

I don't want that ERRNO of 1 above because lein-ancient was displeased with the dependencies.  They all work, they just apparently can't provide lein-ancient with what it needs to confirm them.

**Comment by xsc** [comment]
@robertkuhar I do agree that this broke backwards-compatibility, albeit regarding a feature there never was an explicit contract for before the change. I apologise for the inconveniences you experienced.

That said, I think the current behaviour is the right one to offer by default. lein-ancient is a tool to check projects for outdated dependencies – the result of which might interest both humans and other tools. Using the status code to communicate facts like this does seem like common practice to me.

I'm not opposed to adding a flag disabling this behaviour, though, and I'll gladly accept a PR on that topic. The function generating the exit code is [here](https://github.com/xsc/lein-ancient/blob/master/src/leiningen/ancient/check.clj#L26-L31), with command line flags being managed [here](https://github.com/xsc/lein-ancient/blob/master/src/leiningen/ancient/cli.clj#L7). It should be possible to achieve your desired behaviour with minimal adjustments.

I'm wondering, however, where you're running the command you provided. If locally and just for yourself, why are you interested in the exit code? If on CI, why would you make a purely informational step part of your test command? (I mean, there is a multitude of other reasons lein-ancient can fail and you wouldn't want your tests to go red just because of that.)

**Comment by robertkuhar** [comment]
The example I gave was running it locally where I figured out what was
happening on lein-ancient 0.6.10 that wasn't happening in 0.5.5.  This
change in behavior actually hurts me on our build box where its now failing
some convoluted Jenkins job.  I was ranting on some other ticket here and a
suggestion was made to configure this like...

lein ancient || true

...which should work really well to work around this.

In any event, thanks for getting back to me and the function of the tool is
really great.  I just need to figure out whether its output should fail my
builds or not and work around as needed.


Bob
